version: 1.0.{build}
os: Windows Server 2012 R2
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  ConnectionString: mongodb://localhost
  TableName: tumblr_downloader
  PhotosDirectory: D:\tumblrphotos
  ConsumerKey:
    secure: dfc4y6NH+KFsAEory0EzAlblzOCM24ndBAhIlI2Hw4hut5HdzI4MgIxU5gM9Vk1fEpOTtejfROYdGDjsiwy64A==
  ConsumerSecret:
    secure: H7qv/O4zuHkV9jHfKUXG0Gcn8+/9o1R2q5yRLKQu223bo8IuNoAStjg5FfLgRD3i/RqSa6K9KzM6qcML/I0TUg==
install:
- cinst mongodb
before_build:
- ps: tools\Setup-ConfigFiles.ps1
- nuget restore
build:
  verbosity: minimal
test: off
deploy: off