// <auto-generated />
namespace Icm.TumblrDownloader.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DownloadFile_DownloadDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DownloadFile_DownloadDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201409231844305_DownloadFile_DownloadDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
